#!/bin/bash

arm-linux-gnueabihf-gcc \
        -isystem/opt/rpi-fs/usr/include/arm-linux-gnueabihf \
        -isystem/opt/rpi-fs/usr/include \
        -L/opt/rpi-fs/usr/lib/arm-linux-gnueabihf \
        -L/opt/rpi-fs/usr/lib \
        $@

