#!/bin/bash

docker run -it --rm \
	-v $(pwd):/source \
	-v ~/.cargo/git:/root/.cargo/git \
	-v ~/.cargo/registry:/root/.cargo/registry \
	dlecan/rust-crosscompiler-armv6:stable "$@"

sudo chown -R `stat -c %u:%g $HOME` $(pwd) ~/.cargo
